image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip install -r requirements.txt
      npm install --prefix react-app
  - command: |
      (python manage.py runserver 0.0.0.0:8000 &) && (cd react-app && npm start)

ports:
  - port: 8000
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
    - dbaeumer.vscode-eslint
    - GitHub.vscode-github-actions
